---
title: Een sprite uit een bestand toevoegen
hero_image: images/banner.png
description: Een sprite in Scratch toevoegen vanuit een bestand
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - title: Een sprite uit een bestand toevoegen
