---
title: Een sprite uit een bestand toevoegen
hero_image: images/banner.png
description: Adding a sprite from a file in Scratch
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Adding a sprite from a file
