title: generic-scratch3-add-sprite-from-file
hero_image: images/banner.png
description: generic-scratch3-add-sprite-from-file description
version: 4
listed: false
copyedit: false
last_tested: "2018-11-05"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
