---
title: फाइलमधून एक स्प्राईट जोडणे
hero_image: images/banner.png
description: Scratch मधील फाईलमधून स्प्राइट जोडणे
duration: 0
listed: false
ingredient: true
copyedit: true
steps:
  - title: फाइलमधून एक स्प्राईट जोडणे
