---
title: Добавление спрайта из файла
hero_image: images/banner.png
description: Добавление спрайта из файла в Scratch
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Добавление спрайта из файла
