---
title: किसी फ़ाइल से sprite जोड़ना
hero_image: images/banner.png
description: Scratch में एक file से sprite जोड़ना
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: किसी फ़ाइल से sprite जोड़ना
