---
title: Legge til en figur fra en fil
hero_image: images/banner.png
description: Legge til en figur fra en fil i Scratch
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - title: Legge til en figur fra en fil
