---
title: Adicionar um actor a partir de um ficheiro
hero_image: images/banner.png
description: Adicionar um actor a partir de um ficheiro no Scratch
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Adicionar um actor a partir de um ficheiro
