---
title: اضافه کردن یک شکلک از طریق یک فایل
hero_image: images/banner.png
description: افزودن یک شکلک از طریق یک فایل در اسکرچ
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - title: اضافه کردن یک شکلک از طریق یک فایل
