---
title: Ein Objekt aus einer Datei hinzufügen
hero_image: images/banner.png
description: Ein Objekt aus einer Datei in Scratch hinzufügen
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - title: Ein Objekt aus einer Datei hinzufügen
