---
title: Adicionando um sprite a partir de um arquivo
hero_image: imagens/banner.png
description: Adicionando um sprite a partir de um arquivo no Scratch
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Adicionando um sprite a partir de um arquivo
