---
title: Dodajanje figure iz datoteke
hero_image: images/banner.png
description: Dodajanje figure iz datoteke v Scratchu
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - title: Dodajanje figure iz datoteke
