---
title: Añadir un objeto desde un archivo
hero_image: images/banner.png
description: Añadir un objeto desde un archivo en Scratch
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Añadir un objeto desde un archivo
