---
title: Προσθέτοντας ένα αντικείμενο από ένα αρχείο
hero_image: images/banner.png
description: Προσθέτοντας ένα sprite από ένα αρχείο στο Scratch
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Προσθέτοντας ένα sprite από ένα αρχείο
