---
title: Ajouter un sprite à partir d'un fichier
hero_image: images/banner.png
description: Ajouter un sprite à partir d'un fichier dans Scratch
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Ajouter un sprite à partir d'un fichier
