---
title: ගොනුවකින් ස්ප්‍රයිට් එකතු කිරීම
hero_image: images / banner.png
description: ගොනුවක් මගින් Scratch වලට sprite එකක් එකතු කිරීමට
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: ගොනුවකින් sprite එකතු කිරීම
