---
title: Dosyadan kukla ekleme
hero_image: images/banner.png
description: Scratch'te dosyadan bir kukla ekleme
duration: 1
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: Dosyadan kukla ekleme
